import Link from "next/link";
import {
  Mic,
  Brain,
  Volume2,
  Puzzle,
  Settings2,
  ShieldCheck,
  Check,
  ChevronRight,
  Zap,
  Github,
  Twitter,
  MessageSquare,
  Hash,
  Volume1,
  Circle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FAQAccordion } from "@/components/landing/faq-accordion";
import { cn } from "@/lib/utils";

// ─── Data ──────────────────────────────────────────────────────────────────────

const features = [
  {
    icon: Mic,
    title: "Wake Word Detection",
    description:
      'Say "Nocta" from anywhere in the voice channel. Powered by Picovoice Porcupine — on-device, zero latency, zero false positives.',
  },
  {
    icon: Brain,
    title: "Claude AI Brain",
    description:
      "Every response is generated by Anthropic's Claude — the same model behind Claude.ai. Context-aware, nuanced, and genuinely intelligent.",
  },
  {
    icon: Volume2,
    title: "Natural Voice Synthesis",
    description:
      "Responses are spoken aloud in a natural human voice via ElevenLabs. Turbo model keeps latency under 500ms from query to audio.",
  },
  {
    icon: Puzzle,
    title: "Modular System",
    description:
      "Enable only what your server needs — music controls, moderation, trivia, and more. Each guild has its own independent module stack.",
  },
  {
    icon: Settings2,
    title: "Per-Server Config",
    description:
      "Prefix, language, welcome messages, log channels, role assignments — every setting is scoped to your server and yours alone.",
  },
  {
    icon: ShieldCheck,
    title: "Privacy First",
    description:
      "Audio is processed in real-time and never stored or logged. Only the transcribed text is sent to Claude. Your conversations stay private.",
  },
];

const steps = [
  {
    number: "01",
    title: "Add NOCTA to your server",
    description:
      'Click "Add to Discord", authorise the bot, and pick the server. Setup takes under 30 seconds.',
  },
  {
    number: "02",
    title: 'Say "Nocta" in a voice channel',
    description:
      "Join any voice channel and say the wake word. NOCTA will chime to confirm it's listening.",
  },
  {
    number: "03",
    title: "Ask anything, hear the answer",
    description:
      "Speak your question naturally. NOCTA transcribes it, thinks with Claude, and replies aloud in seconds.",
  },
];

const plans = [
  {
    name: "Free",
    price: "$0",
    period: "forever",
    description: "Perfect for trying NOCTA in your community.",
    featured: false,
    cta: "Get started",
    features: [
      "50 voice queries / day",
      "2 active modules",
      "Basic Claude responses",
      "Standard voice",
      "Community support",
    ],
  },
  {
    name: "Pro",
    price: "$9",
    period: "per month",
    description: "For active communities that rely on NOCTA daily.",
    featured: true,
    cta: "Start free trial",
    features: [
      "Unlimited voice queries",
      "All modules included",
      "Extended Claude responses",
      "Premium ElevenLabs voices",
      "Custom server prefix",
      "Priority support",
    ],
  },
  {
    name: "Premium",
    price: "$24",
    period: "per month",
    description: "For power users and large multi-server communities.",
    featured: false,
    cta: "Contact us",
    features: [
      "Everything in Pro",
      "Up to 5 Discord servers",
      "Custom wake word",
      "REST API access",
      "Dedicated support",
      "Early feature access",
    ],
  },
];

const faqs = [
  {
    question: "What is NOCTA?",
    answer:
      "NOCTA is an AI-powered voice assistant for Discord. It listens passively in your voice channel and activates when it hears the wake word \"Nocta\". Once activated, it transcribes your question, sends it to Claude AI, and speaks the response back through your voice channel in real time.",
  },
  {
    question: "What Discord permissions does NOCTA need?",
    answer:
      "NOCTA requires Connect and Speak permissions in voice channels to join and play audio. It also needs Read Messages and Send Messages in text channels for the slash commands (/join, /leave, /nocta, /modules, /settings). It does not require administrator permissions.",
  },
  {
    question: "How accurate is the wake word detection?",
    answer:
      "Wake word detection is handled by Picovoice Porcupine, which runs on-device with very high accuracy. At the default 0.5 sensitivity setting, false positive rates are extremely low. If you experience missed detections, you can increase sensitivity in your server settings.",
  },
  {
    question: "Can I customise NOCTA's voice?",
    answer:
      "Pro and Premium plans can choose from any ElevenLabs voice in the library, including cloned voices. Free plan uses a default high-quality voice. Premium plan additionally allows you to create a fully custom voice for your server.",
  },
  {
    question: "Is my audio stored or shared?",
    answer:
      "No. Audio is processed in real-time and discarded immediately after transcription. Only the text transcript is sent to Claude AI. We do not record, store, or share any voice data. Transcripts are also not retained beyond the current session.",
  },
  {
    question: "How do I cancel or change my plan?",
    answer:
      "You can upgrade, downgrade, or cancel at any time from the dashboard under Billing. Cancellations take effect at the end of the current billing period and you retain full access until then. No questions asked.",
  },
];

// ─── Navbar ────────────────────────────────────────────────────────────────────

function Navbar() {
  return (
    <header className="fixed inset-x-0 top-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-md">
      <nav className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6">
        {/* Logo */}
        <Link href="/" className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-600 text-sm font-bold text-white">
            N
          </div>
          <span className="font-semibold tracking-tight text-white">NOCTA</span>
        </Link>

        {/* Desktop nav */}
        <div className="hidden items-center gap-6 text-sm text-muted-foreground md:flex">
          <Link href="#features" className="transition-colors hover:text-white">Features</Link>
          <Link href="#how-it-works" className="transition-colors hover:text-white">How it works</Link>
          <Link href="#pricing" className="transition-colors hover:text-white">Pricing</Link>
          <Link href="#faq" className="transition-colors hover:text-white">FAQ</Link>
        </div>

        {/* CTA */}
        <Button
          asChild
          size="sm"
          className="bg-violet-600 hover:bg-violet-500 text-white hidden sm:inline-flex"
        >
          <Link href="https://discord.com/oauth2/authorize" target="_blank">
            Add to Discord
            <ChevronRight size={14} className="ml-1" />
          </Link>
        </Button>
      </nav>
    </header>
  );
}

// ─── Hero ──────────────────────────────────────────────────────────────────────

function DiscordMockup() {
  return (
    <div className="w-full overflow-hidden rounded-2xl border border-[#202225] shadow-2xl">
      <div className="flex h-full">
        {/* Sidebar */}
        <div className="flex w-48 flex-shrink-0 flex-col bg-[#2f3136]">
          {/* Server icon */}
          <div className="flex h-12 items-center gap-2 border-b border-[#202225] px-3">
            <div className="flex h-6 w-6 items-center justify-center rounded-lg bg-violet-600 text-[10px] font-bold text-white">
              N
            </div>
            <span className="text-xs font-semibold text-white">NOCTA Server</span>
          </div>
          {/* Channels */}
          <div className="flex-1 p-2 text-xs">
            <p className="px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-[#72767d]">
              Text channels
            </p>
            <div className="flex items-center gap-1.5 rounded px-2 py-1 text-[#dcddde] hover:bg-[#393c43]">
              <Hash size={13} className="text-[#72767d]" />
              <span>general</span>
            </div>
            <div className="flex items-center gap-1.5 rounded bg-[#393c43] px-2 py-1 text-white">
              <Hash size={13} className="text-[#72767d]" />
              <span>nocta-logs</span>
            </div>
            <p className="mt-2 px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-[#72767d]">
              Voice channels
            </p>
            <div className="flex flex-col gap-0.5 rounded bg-[#393c43] px-2 py-1">
              <div className="flex items-center gap-1.5 text-white">
                <Volume1 size={13} className="text-[#72767d]" />
                <span>General</span>
              </div>
              {/* Users in channel */}
              <div className="ml-4 flex items-center gap-1.5 py-0.5 text-[#b9bbbe]">
                <div className="h-4 w-4 rounded-full bg-blue-500" />
                <span className="text-[11px]">Alex</span>
              </div>
              <div className="ml-4 flex items-center gap-1.5 py-0.5">
                <div className="relative h-4 w-4 flex-shrink-0 rounded-full bg-violet-600">
                  <Circle
                    size={6}
                    className="absolute -bottom-0.5 -right-0.5 fill-green-500 text-green-500"
                  />
                </div>
                <span className="text-[11px] font-medium text-green-400">NOCTA</span>
              </div>
            </div>
          </div>
          {/* User area */}
          <div className="border-t border-[#202225] bg-[#292b2f] px-2 py-2 flex items-center gap-2">
            <div className="h-6 w-6 rounded-full bg-blue-500" />
            <span className="text-[11px] text-[#dcddde]">Alex</span>
          </div>
        </div>

        {/* Main chat */}
        <div className="flex flex-1 flex-col bg-[#36393f]">
          {/* Channel header */}
          <div className="flex h-12 items-center gap-2 border-b border-[#202225] px-4">
            <Hash size={16} className="text-[#72767d]" />
            <span className="text-sm font-semibold text-white">nocta-logs</span>
          </div>
          {/* Messages */}
          <div className="flex-1 space-y-4 overflow-hidden p-4">
            {/* User message */}
            <div className="flex gap-3">
              <div className="h-8 w-8 flex-shrink-0 rounded-full bg-blue-500" />
              <div>
                <div className="flex items-baseline gap-2">
                  <span className="text-sm font-semibold text-white">Alex</span>
                  <span className="text-[10px] text-[#72767d]">Today at 4:12 PM</span>
                </div>
                <p className="mt-0.5 text-sm text-[#dcddde]">
                  nocta, summarise today&apos;s announcements
                </p>
              </div>
            </div>
            {/* NOCTA response */}
            <div className="flex gap-3">
              <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-violet-600 text-xs font-bold text-white">
                N
              </div>
              <div>
                <div className="flex items-baseline gap-2">
                  <span className="text-sm font-semibold text-violet-400">NOCTA</span>
                  <span className="text-[10px] text-[#72767d]">Today at 4:12 PM</span>
                  <span className="rounded bg-violet-600/20 px-1 py-0.5 text-[9px] font-medium text-violet-400">
                    BOT
                  </span>
                </div>
                <p className="mt-0.5 text-sm text-[#dcddde]">
                  Sure! Today&apos;s announcements cover the new v2.0 release with voice
                  module support, the scheduled maintenance on Saturday at 2 AM UTC, and
                  a community AMA next Friday.
                </p>
              </div>
            </div>
            {/* Typing indicator */}
            <div className="flex items-center gap-2 text-[11px] text-[#72767d]">
              <div className="flex gap-0.5">
                <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#72767d] [animation-delay:0ms]" />
                <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#72767d] [animation-delay:150ms]" />
                <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#72767d] [animation-delay:300ms]" />
              </div>
              NOCTA is listening…
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function Hero() {
  return (
    <section className="relative overflow-hidden pt-28 pb-20 sm:pt-36 sm:pb-28">
      {/* Background glow */}
      <div className="pointer-events-none absolute inset-0 grid-bg opacity-100" />
      <div className="pointer-events-none absolute left-1/2 top-0 h-[600px] w-[900px] -translate-x-1/2 rounded-full bg-violet-600/10 blur-[120px]" />

      <div className="relative mx-auto max-w-6xl px-4 sm:px-6">
        <div className="grid gap-12 lg:grid-cols-2 lg:items-center lg:gap-16">
          {/* Left — copy */}
          <div className="flex flex-col items-start gap-6">
            <Badge>
              <Zap size={11} />
              Powered by Claude AI &amp; ElevenLabs
            </Badge>

            <h1 className="text-4xl font-extrabold leading-tight tracking-tight sm:text-5xl lg:text-6xl">
              Your Discord&apos;s{" "}
              <span className="text-gradient">AI Voice</span>
              <br />
              Assistant
            </h1>

            <p className="max-w-lg text-base leading-relaxed text-muted-foreground sm:text-lg">
              Say <span className="font-semibold text-violet-400">&ldquo;Nocta&rdquo;</span> in any
              voice channel and get instant, spoken AI answers — powered by Anthropic Claude and
              natural ElevenLabs voices.
            </p>

            <div className="flex flex-wrap gap-3">
              <Button
                asChild
                size="lg"
                className="bg-violet-600 hover:bg-violet-500 text-white glow-violet-sm"
              >
                <Link href="https://discord.com/oauth2/authorize" target="_blank">
                  Add to Discord — it&apos;s free
                  <ChevronRight size={16} className="ml-1" />
                </Link>
              </Button>
              <Button asChild size="lg" variant="outline" className="border-border hover:bg-secondary">
                <Link href="#how-it-works">See how it works</Link>
              </Button>
            </div>

            {/* Social proof stats */}
            <div className="flex flex-wrap gap-6 pt-2">
              {[
                { value: "12,000+", label: "Discord servers" },
                { value: "2M+", label: "Voice queries" },
                { value: "4.9 ★", label: "Average rating" },
              ].map((stat) => (
                <div key={stat.label}>
                  <p className="text-xl font-bold text-white">{stat.value}</p>
                  <p className="text-xs text-muted-foreground">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Right — Discord mockup */}
          <div className="relative hidden lg:block">
            <div className="absolute -inset-4 rounded-3xl bg-violet-600/5 blur-xl" />
            <div className="relative">
              <DiscordMockup />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Features ──────────────────────────────────────────────────────────────────

function Features() {
  return (
    <section id="features" className="py-20 sm:py-28">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        {/* Header */}
        <div className="mx-auto mb-14 max-w-2xl text-center">
          <Badge className="mb-4">Features</Badge>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Everything your server needs
          </h2>
          <p className="mt-4 text-muted-foreground">
            NOCTA combines state-of-the-art AI with seamless Discord integration — all in one bot.
          </p>
        </div>

        {/* Grid */}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {features.map(({ icon: Icon, title, description }) => (
            <div
              key={title}
              className="group rounded-xl border border-border bg-card p-6 transition-all duration-300 hover:border-violet-500/30 hover:bg-violet-500/5"
            >
              <div className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-lg bg-violet-600/15 text-violet-400 transition-colors group-hover:bg-violet-600/25">
                <Icon size={20} />
              </div>
              <h3 className="mb-2 font-semibold text-white">{title}</h3>
              <p className="text-sm leading-relaxed text-muted-foreground">{description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── How it works ──────────────────────────────────────────────────────────────

function HowItWorks() {
  return (
    <section id="how-it-works" className="py-20 sm:py-28">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        {/* Header */}
        <div className="mx-auto mb-14 max-w-2xl text-center">
          <Badge className="mb-4">How it works</Badge>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Up and running in minutes
          </h2>
          <p className="mt-4 text-muted-foreground">
            No complicated setup. No hardware required. Just a Discord server and your voice.
          </p>
        </div>

        {/* Steps */}
        <div className="relative grid gap-8 lg:grid-cols-3">
          {/* Connecting line (desktop) */}
          <div className="pointer-events-none absolute left-0 right-0 top-8 hidden h-px bg-gradient-to-r from-transparent via-border to-transparent lg:block" />

          {steps.map(({ number, title, description }) => (
            <div key={number} className="relative flex flex-col items-center text-center">
              {/* Step number */}
              <div className="relative mb-6 flex h-16 w-16 items-center justify-center rounded-2xl border border-violet-500/30 bg-violet-600/15 glow-violet-sm">
                <span className="text-xl font-bold text-violet-400">{number}</span>
              </div>
              <h3 className="mb-3 text-lg font-semibold text-white">{title}</h3>
              <p className="text-sm leading-relaxed text-muted-foreground">{description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Pricing ───────────────────────────────────────────────────────────────────

function Pricing() {
  return (
    <section id="pricing" className="py-20 sm:py-28">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        {/* Header */}
        <div className="mx-auto mb-14 max-w-2xl text-center">
          <Badge className="mb-4">Pricing</Badge>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Simple, transparent pricing
          </h2>
          <p className="mt-4 text-muted-foreground">
            Start for free. Upgrade when you&apos;re ready. No hidden fees, no contracts.
          </p>
        </div>

        {/* Cards */}
        <div className="grid gap-6 lg:grid-cols-3 lg:items-stretch">
          {plans.map((plan) => (
            <div
              key={plan.name}
              className={cn(
                "relative flex flex-col rounded-2xl border p-8 transition-all",
                plan.featured
                  ? "border-violet-500 bg-gradient-to-b from-violet-950/40 to-card glow-violet"
                  : "border-border bg-card",
              )}
            >
              {plan.featured && (
                <div className="absolute -top-3.5 left-1/2 -translate-x-1/2">
                  <Badge className="shadow-lg">Most popular</Badge>
                </div>
              )}

              <div className="mb-6">
                <h3 className="mb-1 text-lg font-bold text-white">{plan.name}</h3>
                <div className="mb-3 flex items-baseline gap-1">
                  <span className="text-4xl font-extrabold text-white">{plan.price}</span>
                  <span className="text-sm text-muted-foreground">/{plan.period}</span>
                </div>
                <p className="text-sm text-muted-foreground">{plan.description}</p>
              </div>

              <ul className="mb-8 flex-1 space-y-3">
                {plan.features.map((feature) => (
                  <li key={feature} className="flex items-center gap-3 text-sm">
                    <Check
                      size={15}
                      className={plan.featured ? "text-violet-400" : "text-muted-foreground"}
                    />
                    <span className={plan.featured ? "text-foreground" : "text-muted-foreground"}>
                      {feature}
                    </span>
                  </li>
                ))}
              </ul>

              <Button
                asChild
                className={cn(
                  "w-full",
                  plan.featured
                    ? "bg-violet-600 hover:bg-violet-500 text-white"
                    : "border-border bg-transparent hover:bg-secondary text-foreground",
                )}
                variant={plan.featured ? "default" : "outline"}
              >
                <Link href="https://discord.com/oauth2/authorize" target="_blank">
                  {plan.cta}
                </Link>
              </Button>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── FAQ ───────────────────────────────────────────────────────────────────────

function FAQ() {
  return (
    <section id="faq" className="py-20 sm:py-28">
      <div className="mx-auto max-w-3xl px-4 sm:px-6">
        <div className="mb-14 text-center">
          <Badge className="mb-4">FAQ</Badge>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Frequently asked questions
          </h2>
          <p className="mt-4 text-muted-foreground">
            Can&apos;t find the answer you&apos;re looking for?{" "}
            <Link
              href="https://discord.gg/nocta"
              className="text-violet-400 underline-offset-4 hover:underline"
              target="_blank"
            >
              Ask in our Discord
            </Link>
            .
          </p>
        </div>
        <FAQAccordion items={faqs} />
      </div>
    </section>
  );
}

// ─── CTA Banner ────────────────────────────────────────────────────────────────

function CTABanner() {
  return (
    <section className="py-16 sm:py-20">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="relative overflow-hidden rounded-2xl border border-violet-500/20 bg-gradient-to-br from-violet-950/60 via-card to-card p-10 text-center glow-violet-sm sm:p-16">
          {/* Background orb */}
          <div className="pointer-events-none absolute left-1/2 top-0 h-64 w-96 -translate-x-1/2 -translate-y-1/2 rounded-full bg-violet-600/20 blur-[80px]" />

          <div className="relative">
            <h2 className="mb-4 text-3xl font-bold tracking-tight text-white sm:text-4xl">
              Ready to give your server a voice?
            </h2>
            <p className="mx-auto mb-8 max-w-xl text-muted-foreground">
              Join 12,000+ Discord communities already using NOCTA. Free to start, no credit card
              required.
            </p>
            <Button
              asChild
              size="lg"
              className="bg-violet-600 hover:bg-violet-500 text-white glow-violet-sm"
            >
              <Link href="https://discord.com/oauth2/authorize" target="_blank">
                Add NOCTA to Discord — free
                <ChevronRight size={16} className="ml-1" />
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Footer ────────────────────────────────────────────────────────────────────

function Footer() {
  return (
    <footer className="border-t border-border">
      <div className="mx-auto max-w-6xl px-4 py-12 sm:px-6">
        <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4">
          {/* Brand */}
          <div className="lg:col-span-2">
            <div className="mb-4 flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-600 text-sm font-bold text-white">
                N
              </div>
              <span className="font-semibold text-white">NOCTA</span>
            </div>
            <p className="max-w-xs text-sm leading-relaxed text-muted-foreground">
              The AI voice assistant built for Discord. Say the word, get the answer.
            </p>
            <div className="mt-4 flex gap-3">
              <Link
                href="https://github.com/Sergi-Marin/NOCTA"
                target="_blank"
                className="text-muted-foreground transition-colors hover:text-white"
              >
                <Github size={18} />
              </Link>
              <Link
                href="https://twitter.com"
                target="_blank"
                className="text-muted-foreground transition-colors hover:text-white"
              >
                <Twitter size={18} />
              </Link>
              <Link
                href="https://discord.gg/nocta"
                target="_blank"
                className="text-muted-foreground transition-colors hover:text-white"
              >
                <MessageSquare size={18} />
              </Link>
            </div>
          </div>

          {/* Product */}
          <div>
            <h4 className="mb-4 text-sm font-semibold text-white">Product</h4>
            <ul className="space-y-3 text-sm text-muted-foreground">
              {["Features", "Pricing", "Changelog", "Roadmap"].map((item) => (
                <li key={item}>
                  <Link href="#" className="transition-colors hover:text-white">
                    {item}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Company */}
          <div>
            <h4 className="mb-4 text-sm font-semibold text-white">Legal</h4>
            <ul className="space-y-3 text-sm text-muted-foreground">
              {["Privacy Policy", "Terms of Service", "Cookie Policy", "Contact"].map((item) => (
                <li key={item}>
                  <Link href="#" className="transition-colors hover:text-white">
                    {item}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="mt-10 flex flex-col items-center justify-between gap-4 border-t border-border pt-8 text-sm text-muted-foreground sm:flex-row">
          <p>© {new Date().getFullYear()} NOCTA. All rights reserved.</p>
          <p>
            Built with{" "}
            <Link
              href="https://nextjs.org"
              target="_blank"
              className="transition-colors hover:text-white"
            >
              Next.js
            </Link>{" "}
            &amp;{" "}
            <Link
              href="https://anthropic.com"
              target="_blank"
              className="transition-colors hover:text-white"
            >
              Anthropic Claude
            </Link>
          </p>
        </div>
      </div>
    </footer>
  );
}

// ─── Page ──────────────────────────────────────────────────────────────────────

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navbar />
      <main>
        <Hero />
        <Features />
        <HowItWorks />
        <Pricing />
        <FAQ />
        <CTABanner />
      </main>
      <Footer />
    </div>
  );
}
